class GPIO_CODERBOT_V_4():
    # motors
    PIN_MOTOR_ENABLE = 22
    PIN_RIGHT_FORWARD = 24
    PIN_RIGHT_BACKWARD = 25
    PIN_LEFT_FORWARD = 17
    PIN_LEFT_BACKWARD = 4

    PIN_PUSHBUTTON = 11
    # servo
    PIN_SERVO_1 = 9
    PIN_SERVO_2 = 10
    # sonar
    PIN_SONAR_1_TRIGGER = 18
    PIN_SONAR_1_ECHO = 7
    PIN_SONAR_2_TRIGGER = 18
    PIN_SONAR_2_ECHO = 8
    PIN_SONAR_3_TRIGGER = 18
    PIN_SONAR_3_ECHO = 23
    PIN_SONAR_4_TRIGGER = 18
    PIN_SONAR_4_ECHO = None

    # encoder
    PIN_ENCODER_LEFT_A = 14
    PIN_ENCODER_LEFT_B = 6
    PIN_ENCODER_RIGHT_A = 15
    PIN_ENCODER_RIGHT_B = 12